# Utilise PostGIS comme base (Postgres 16 + PostGIS 3.4)
FROM postgis/postgis:16-3.4

# Installe pgRouting + GDAL (ogr2ogr inclus dans gdal-bin)
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-16-pgrouting \
        gdal-bin \
    && rm -rf /var/lib/apt/lists/*

# Juste pour être sûr que Postgres voit bien PostGIS et pgRouting
RUN echo "PostGIS + pgRouting + GDAL installed"
