-- SQL/04_graph/03_views/routing_vertices.sql
-- Purpose: 
-- Provides a stable, canonical view of routing vertices for all routing algorithms.
--
-- Usage:
-- - All routing and routing-dependent functions MUST query this view
--   instead of accessing the underlying table directly.
-- - The underlying table may change (versioning, imports, schema),
--   while this view preserves a stable internal contract.
--
-- Notes:
--- - This view relies on the vertices table generated by pgr_createTopology.
-- - The routing graph must be built beforehand for this view to return data.

\echo ''
\echo '>>> START : SQL/04_graph/03_views/routing_vertices.sql'
\echo ''

CREATE OR REPLACE VIEW routing_vertices AS
SELECT
  id,
  the_geom,
  chk
FROM public.routes_v1_vertices_pgr;

\echo ''
\echo '<<< END   : SQL/04_graph/03_views/routing_vertices.sql'
\echo ''